services:
  - type: web
    name: webrtc-video-platform-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        scope: build,runtime
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        scope: build,runtime
